### ISSUE TITLE
[0.4.3] crash on server

### ISSUE THREAD

**Issue by MSandro** [paulevsGitch/BCLib#37]
```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/4/21, 9:25 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/fabricmc/loader/impl/metadata/ModMetadataParser
	at ru.bclib.util.ModUtil.lambda$getMods$0(ModUtil.java:60)
	at ru.bclib.util.PathUtil.fileWalker(PathUtil.java:73)
	at ru.bclib.util.ModUtil.getMods(ModUtil.java:51)
	at ru.bclib.api.dataexchange.handler.autosync.HelloClient.serializeDataOnServer(HelloClient.java:86)
	at ru.bclib.api.dataexchange.DataHandler$FromServer.sendToClient(DataHandler.java:262)
	at ru.bclib.api.dataexchange.BaseDataHandler.reply(BaseDataHandler.java:47)
	at ru.bclib.api.dataexchange.handler.autosync.HelloServer.runOnServerGameThread(HelloServer.java:106)
	at ru.bclib.api.dataexchange.DataHandler$FromClient.lambda$receiveFromClient$0(DataHandler.java:165)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.metadata.ModMetadataParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 4.4.0-154-generic
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	JVM Flags: 18 total; -Xmx3250M -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.3
		adorn: Adorn 2.2.0+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		ae2wtlib: AE2WTLib 9.0.0-beta.7
		agape_space: Space Dimensions 0.3.4
		alloy_forgery: Alloy Forgery 2.0.5
		aopalliance_aopalliance: aopalliance 1.0
		appleskin: AppleSkin mc1.17-2.1.3
		appletreesrev: Apple Trees Rev. 2.5
		appliedenergistics2: Applied Energistics 2 9.0.0-beta.1
		arcanus: Arcanus 1.22
		architectury: Architectury 2.6.35
		artofalchemy: Art of Alchemy: Memoriam 1.2.0+1.17.1
		auto_planter: AutoPlanter 17.1-fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.24+MC1.17-1.17.1
		awesomedungeon: Awesome Dungeon 1.1.2
		awokenworld: Awoken World 2.0.0
		balm-fabric: Balm 1.3.0+0
		barrenisles: Barren Isles 1.0.7
		bclib: BCLib 0.4.3
		beaconoverhaul: Beacon Overhaul 1.4.2+1.17
		bedbenefitsfabric: Bed Benefits 1.17.1-0.1.1
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.12.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bewitchment: Bewitchment 1.17-12
		bitsandchisels: BitsAndChisels 2.5.3
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		blockus: Blockus 2.2.10+1.17.1
		blue_endless_jankson: jankson 1.2.1
		buildinggadgets: st'ructure tools 1.0.1
		campanion: Campanion 2.0.0-beta.1
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.1
		charm: Charm 3.3.2
		chipped: Chipped 1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 7.0.10
		collective-fabric: Collective (Fabric) 1.61
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.0-rc2
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.0-rc2
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.0-rc2
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0-rc2
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.13.0-rc2
		com_flowpowered_flow-math: flow-math 1.0.3
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
		com_google_inject_guice: guice 5.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.7-1.17.1
		completeconfig: CompleteConfig 1.1.0
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		conjuring: Conjuring 1.0.14
		couplings: Couplings 1.5.0+1.17
		craftingtweaks: Crafting Tweaks 13.0.0+0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta37-1.17
		customspawns: Custom Spawns 0.5+1.17
		danceofgrowth: Twerk / Crop Dusting Mod 1.0
		dankstorage: Dank Storage 2.2.1-1.17.1
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		datapackportals: Datapack Portals 1.0.4-1.17
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		dimdoors: DimensionalDoors 4.0.0+beta.3-27.10.2021
		dispenser_configurator: Dispenser Configurator 1.1.1+MC1.17-1.17.1
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		enhanced_quarries: Enhanced Quarries 1.2.0_RC7
		expandedstorage: Expanded Storage 7.2.7
		extraalchemy: Extra Alchemy 1.6.1
		extragenerators: Extra Generators 1.1-BETA+1.17
		fabric: Fabric API 0.41.3+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.1+ffbe6d8f18
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-copper-golem: Copper Golem 1.0.1+1.17.1
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.12+ffbe6d8f18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ef17126d18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.12+81e15a8918
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+ffbe6d8f18
		fabrication: Fabrication 2.0.0_01
		fabricloader: Fabric Loader 0.11.7
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		farmersdelight: Farmer's Delight 1.17.1-0.1.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		full_slabs: FullSlabs 3.2.1
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gearreborn: Gear Reborn 1.17-0.1.10
		geckolib3: Geckolib 3.0.20
		glassential: Glassential 1.17-1.2.0
		go-fish: Go Fish 1.3.0-beta-1.17.1
		goblintraders: Goblin Traders 1.2.0
		golemsgalore: Golems Galore 1.0.3-1.17.1
		grass_pass: Grass Bypass 1.0.0
		gunpowder-base: Gunpowder 1.0.6.3+1.17.1
		gunpowder-sleepvote: Gunpowder SleepVote 1.0.5+gunpowder.1.0.0.mc.1.17-rc2
		gunpowder-teleport: Gunpowder Teleport 1.1.0+gunpowder.1.0.4.1.mc.1.17
		gunpowder-utilities: Gunpowder Utilities 1.0.6+gunpowder.1.0.4.2.mc.1.17
		hardcorequesting: Hardcore Questing Mode 1.17.1-5.7.2
		hctm-base: HCTM Base 3.6.2
		hologram-api: Hologram API 0.2.1+1.17.1
		impersonate: Impersonate 2.3.5
		improved-stations: Improved Stations 2.0.7
		indrev: Industrial Revolution 1.11.0-alpha.4
		inmis: Inmis 2.3.2-1.17.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		javax_inject_javax_inject: javax.inject 1
		justenoughkeys: Just Enough Keys 0.2.2
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.3-BETA+1.17
		kjsextras: KubeJS Extras 1.4.0
		ksyxis: Ksyxis 1.1
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1701.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.9.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libmultipart: LibMultiPart 0.6.0
		libnetworkstack: Lib Network Stack 0.5.0
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.3-BETA+1.17
		light-fix: light-fix 1.0.0
		lightestlamp: Lightest Lamps 0.9.3
		lithium: Lithium 0.7.4
		locki: Locki 0.5.0
		magna: Magna 1.5.5-1.17-pre4
		matrix: Matrix 1.0.0
		mcskyblock: MC Skyblock Fabric 1.0.3
		mechanicaldispensers: MechanicalDispensers 3.6
		megane: megane 5.5.0
		megane-applied-energistics-2: megane-applied-energistics-2 5.5.0+9.0.0-alpha.2
		megane-base: megane-base 5.5.0
		megane-extra-generators: megane-extra-generators 5.5.0+1.1-BETA-1.17
		megane-fabric-transfer: megane-fabric-transfer 5.5.0+1.3.0-fc40aa9d18
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.5.0+0.5.7
		megane-industrial-revolution: megane-industrial-revolution 5.5.0+1.11.0-alpha.1
		megane-kibe: megane-kibe 5.5.0+1.9.1-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.5.0+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.5.0+0.5.12
		megane-reborn-core: megane-reborn-core 5.5.0+5.0.8-beta-build.111
		megane-runtime: megane-runtime 5.5.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.5.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 5.5.0+5.0.8-beta-build.111
		megane-vanilla: megane-vanilla 5.5.0+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.5.0+1.3.0
		minecraft: Minecraft 1.17.1
		mo_glass: Mo Glass 1.5-MC1.17.1
		modern_industrialization: Modern Industrialization 0.6.1
		more_codecs: More Codecs 0.1.4
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		morevillagesmod: More Villages Mod 1.0.0
		moss_fix: Moss Fix 1.1.0
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mtq-fix: MTQ Fix 0.2.2
		myron: Myron 1.6.1
		mysql_mysql-connector-java: mysql-connector-java 8.0.25
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.4
		oldfishfarm: One Block Fish Farm 1.0.0
		omega-config: OmegaConfig 1.0.8
		org_apache_commons_commons-compress: commons-compress 1.19
		org_jetbrains_annotations: annotations 19.0.0
		org_jetbrains_exposed_exposed-core: exposed-core 0.34.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.34.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.34.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		org_objenesis_objenesis: objenesis 3.2
		org_postgresql_postgresql: postgresql 42.2.22
		org_slf4j_slf4j-api: slf4j-api 2.0.0-alpha5
		org_tukaani_xz: xz 1.8
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
		org_yaml_snakeyaml: snakeyaml 1.29
		owo: oωo 0.3.0
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		paintingcycle: Painting Cycle 1.0.0
		patchouli: Patchouli 1.17.1-56-FABRIC
		pehkui: Pehkui 2.5.3+1.14.4-1.18
		permissions-api: Permissions API 0.1.0-alpha1
		placeholder-api: Placeholder API 1.1.1+1.17.1
		plantinajar: Plant In A Jar 2.2.2
		platforms: Platforms 1.1.1
		player-vehicle-desync-fix: Player Vehicle Desync Fix 0.2.2
		player_roles: Player Roles 1.4.3
		player_roles_api: Player Roles API 1.4.3
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.8+1.17.1
		pride: Pride Lib 1.0.0+21w03a
		pugh_lib: Pugh Lib ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.5
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.10-beta
		recipecache: recipecache 0.2.1-1.17.1
		redbits: Red Bits 1.10.1
		repurposed_structures: Repurposed Structures 2.5.1+1.17.1
		resourceful_tools: Resourceful Tools 1.1.21
		resourcemelons: Resource Melons 2.0.0
		rhino: Rhino 1701.1.5-build.71
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.1.314-alpha
		roughlyenoughresources: Roughly Enough Resources 2.2.0
		rswires: RSWires 4.11.2
		scf: Super Cobblestone Funnels 2.1.0
		schmucks: Schmucks 1.4.0
		searchlight: Searchlight 1.1.3
		seasons: Fabric Seasons 1.3.1-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		server_translations_api: Server Translations API 1.4.6+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shetiphiancore: ShetiPhianCore 1.1.1
		shutupconsole: Shut Up Console 1.1
		simple_pipes: SimplePipeTest 0.6.1
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.6.1
		simpletech: SimpleTech 0.0.7
		skyutils: Sky utilities Mod 1.0.5_beta4
		slotlink: slotlink 3.1.6
		smallernetherportals-fabric: Smaller Nether Portals (Fabric) 1.8
		smoothboot: Smooth Boot 1.16.5-1.6.0
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		somnus: Somnus API 0.0.14-1.17.1
		spark: spark 1.6.1
		spatialharvesters: Spatial Harvesters 0.11.12c
		stacc: Stacc 1.2.3
		starry_sky: Starry Skies 1.2.0-1.17.0
		statement: Statement 4.1.3+1.14.4-1.17.1
		statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		steedstopper: Steed Stopper 1.0.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stockpile: Stockpile 1.1.5+1.17.1
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		storagecabinet: Storage Cabinet 1.4.1
		structurized: Structurized 1.3.0
		tatters: Tatters 1.1.0+1.17
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.10-beta
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		textile_backup: Textile Backup 2.2.0-1.17
		the_aether: The Aether 1.17.1-1.5.0
		things: Things 0.2.6
		thonkutil: ThonkUtil 1.2
		timeinabottle: Time in a Bottle 1.6-mc1.17-fabric
		torcherino: Torcherino 15.0.0
		totemmod: Wither Totems Mod 0.3.2
		trapexpansion: Trap Expansion 1.3.3
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		universal-graves: Universal Graves 1.1.3+1.17.1
		victus: Victus 0.1.3+1.17.1
		wands: Building Wands 2.2.7_mc1.17.1
		waystones: Waystones 2.1.2
		winged: Winged Mod 1.17.1-3.0.0
		wireless_redstone: Wireless Redstone 1.0.1
		wirelessnetworks: Wireless Networks 1.3.1
		workings: Workings 1.0.7
		wthit: wthit 3.10.1
		xaerominimap: Xaero's Minimap 21.20.0
		xaeroworldmap: Xaero's World Map 1.18.1
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-19
	Player Count: 1 / 20; [class_3222['MSandro'/3, l='ServerLevel[world]', x=-982.04, y=80.50, z=-995.11]]
	Data Packs: vanilla, Fabric Mods, dimdoors/classic, dimdoors/default, dispenser_configurator/default_dispenser_configurators
	Is Modded: Definitely; Server brand changed to 'Fabric/Gunpowder'
	Type: Dedicated Server (map_server.txt)
```

**Comment by paulevsGitch** [comment]
Update your BCLib
