### ISSUE TITLE
Crash on startup using BCLib 0.5.0, even with the latest better end and better nether updates.

### ISSUE THREAD

**Issue by RelaxAdrian** [paulevsGitch/BCLib#41]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11/12/21, 12:42 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at paulevs.betternether.client.BetterNetherClient.registerRenderLayers(BetterNetherClient.java:21)
		at paulevs.betternether.client.BetterNetherClient.onInitializeClient(BetterNetherClient.java:14)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at io.github.apace100.origins.OriginsClient.onInitializeClient(OriginsClient.java:35)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at io.github.merchantpug.toomanyorigins.TooManyOriginsClient.onInitializeClient(TooManyOriginsClient.java:21)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at ru.bclib.api.PostInitAPI.processBlockClient(PostInitAPI.java:58)
	at ru.bclib.api.PostInitAPI.lambda$postInit$1(PostInitAPI.java:47)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at ru.bclib.api.PostInitAPI.postInit(PostInitAPI.java:44)
	at ru.bclib.client.BCLibClient.onInitializeClient(BCLibClient.java:27)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetUniformLocation(ILjava/lang/CharSequence;)I in sodium.mixins.json:features.shader.MixinShader from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1048756736 bytes (1000 MiB) / 3271557120 bytes (3120 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1069
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 32665.02
	Virtual memory used (MB): 11722.91
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 19.98
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		apoli: Apoli 2.0.5
		appleskin: AppleSkin mc1.17.1-2.2.0
		apugli: Apugli 1.1.6
		architectury: Architectury 2.6.35
		armor-model-predicate: Armor Model Predicate 0.0.1
		attributefix: Attribute Fix {FABRIC} 1.0.3
		basicshields: Basic Shields [Fabric] 1.1.1-1.17.1
		bclib: BCLib 0.5.0
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.12.2
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.3.9
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		calio: Calio 1.3.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cavebiomes: Cave Biomes 0.6.3
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v5 5.1.40
		clumps: Clumps 7.0.10
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dataattributes: Data Attributes 1.0.6
		eatinganimationid: Eating Animation 1.2
		extraorigins: Extra Origins 1.17-10
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.12.5
		fabricshieldlib: Fabric Shield Lib 1.4.5+1.17
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.2
		iris: Iris 1.1.2+build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.5
		minecraft: Minecraft 1.17.1
		moborigins: Mob Origins 1.7.0
		modmenu: Mod Menu 2.0.14
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		net_objecthunter_exp4j: exp4j 0.4.8
		nibbles: Nibbles 1.1.0
		omega-config: OmegaConfig 1.0.8
		origins: Origins 1.1.4
		origins-classes: Origins: Classes 1.2.2
		originsumbrellas: Origins: Umbrellas 1.3.0
		patchouli: Patchouli 1.17.1-56-FABRIC
		paxi: Paxi 1.17-1.2.2
		pehkui: Pehkui 2.5.3+1.14.4-1.18
		placeholder-api: Placeholder API 1.1.1+1.17.1
		playerabilitylib: Pal 1.3.0
		playerex: PlayerEx 3.0.6
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		relicex: RelicEx 3.0.1
		repurposed_structures: Repurposed Structures 2.5.6+1.17.1
		roughlyenoughitems: Roughly Enough Items 6.1.329
		sodium: Sodium 0.3.2+build.7
		toomanyorigins: TooManyOrigins 0.2.3
		travelersbackpack: Traveler's Backpack 1.17.1-6.0.0
		trinkets: Trinkets 3.0.4
		wildfire_gender: Wildfire's Female Gender Mod 2.8
		wthit: wthit 3.11.2
		xaerominimap: Xaero's Minimap 21.21.0
		xaeroworldmap: Xaero's World Map 1.18.1
		yungsapi: YUNG's API 1.17-Fabric-19
	Launched Version: fabric-loader-0.12.5-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by quiqueck** [comment]
It appears to be a compat issue with Sodium in BetterNether. I'll have a look...

**Comment by quiqueck** [comment]
Do you have both Sodium and Iris installed? 
Iris ships with a custom version of Sodium built in, and I am not sure if it is compatible with the standalone Sodium. Form my test logs with iris installed, Sodium should show up as

`- sodium 0.3.2+IRIS2-build.9`

while in the log above it reads
` Sodium 0.3.2+build.7`

Could you please check if that is the case, and if so please remove the standalon Sodium version and let us know if that helped?

**Comment by RelaxAdrian** [comment]
Yes, both sodium and iris are installed. Removing the stand alone sodium did work this time. Thank you!

**Comment by quiqueck** [comment]
Just to wrap up. I can confirm with local tests that Iris or Sodium alone do not trigger the exception. When both are installed I can redroduce the error, but as far as I know, that is not a supported configuration.
