### ISSUE TITLE
Initializing game crash. Issue with bclib 0.5.1

### ISSUE THREAD

**Issue by D3MQ** [paulevsGitch/BCLib#47]
Trying to use better end and better nether with couple other mods but i have issue with bclib 0.5.1. I don't know if i missed some library or something.  Please let me know if u find something in these crash logs.

Using Crystal Launcher
1.17.1 Fabric 0.12.5

Crash log below list of mods and librarys:

Mods and librarys:

![image](https://user-images.githubusercontent.com/89527792/142636169-5e116f99-35a1-4b15-8f5a-987afa607f46.png)

Crash log:

---- Minecraft Crash Report ----
// You're mean.

Time: 11/19/21, 3:08 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bclib'!
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
  at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
  at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
  at net.minecraft.class_310.<init>(class_310.java:457)
  at net.minecraft.client.main.Main.main(Main.java:179)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
  at crystallauncher.MineClient.start(MineClient.java:188)
  at crystallauncher.MineClient.main(MineClient.java:33)
  Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
    at paulevs.betternether.client.BetterNetherClient.registerRenderLayers(BetterNetherClient.java:20)
    at paulevs.betternether.client.BetterNetherClient.onInitializeClient(BetterNetherClient.java:14)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
    ... 18 more
  Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
    at io.github.apace100.origins.OriginsClient.onInitializeClient(OriginsClient.java:35)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
    ... 18 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
  at net.minecraft.class_4668.<clinit>(class_4668.java:125)
  at ru.bclib.api.PostInitAPI.processBlockClient(PostInitAPI.java:58)
  at ru.bclib.api.PostInitAPI.lambda$postInit$1(PostInitAPI.java:47)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at ru.bclib.api.PostInitAPI.postInit(PostInitAPI.java:44)
  at ru.bclib.client.BCLibClient.onInitializeClient(BCLibClient.java:27)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
  ... 18 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
  at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
  at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
  at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
  ... 25 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
  at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
  at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
  at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
  at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
  ... 28 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetUniformLocation(ILjava/lang/CharSequence;)I in sodium.mixins.json:features.shader.MixinShader from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json
  at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
  at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
  at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
  at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
  at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
  at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
  at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
  at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
  ... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
  at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
  at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
  at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
  at net.minecraft.client.main.Main.main(Main.java:179)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
  at crystallauncher.MineClient.start(MineClient.java:188)
  at crystallauncher.MineClient.main(MineClient.java:33)

-- System Details --
Details:
  Minecraft Version: 1.17.1
  Minecraft Version ID: 1.17.1
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 17.0.1, Microsoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
  Memory: 1252865448 bytes (1194 MiB) / 3657433088 bytes (3488 MiB) up to 4194304000 bytes (4000 MiB)
  CPUs: 4
  Processor Vendor: GenuineIntel
  Processor Name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
  Identifier: Intel64 Family 6 Model 94 Stepping 3
  Microarchitecture: Skylake (Client)
  Frequency (GHz): 2.30
  Number of physical packages: 1
  Number of physical CPUs: 4
  Number of logical CPUs: 4
  Graphics card #0 name: Intel(R) HD Graphics 530
  Graphics card #0 vendor: Intel Corporation (0x8086)
  Graphics card #0 VRAM (MB): 1024.00
  Graphics card #0 deviceId: 0x191b
  Graphics card #0 versionInfo: DriverVersion=23.20.16.4973
  Graphics card #1 name: NVIDIA GeForce GTX 960M
  Graphics card #1 vendor: NVIDIA (0x10de)
  Graphics card #1 VRAM (MB): 4095.00
  Graphics card #1 deviceId: 0x139b
  Graphics card #1 versionInfo: DriverVersion=30.0.14.9649
  Memory slot #0 capacity (MB): 8192.00
  Memory slot #0 clockSpeed (GHz): 2.13
  Memory slot #0 type: DDR4
  Virtual memory max (MB): 19202.38
  Virtual memory used (MB): 13884.84
  Swap memory total (MB): 11182.48
  Swap memory used (MB): 1659.52
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4000M -Xms2245M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Fabric Mods: 
    apoli: Apoli 2.0.5
    armor-model-predicate: Armor Model Predicate 0.0.1
    bclib: BCLib 0.5.1
    betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
    betterend: Better End 0.12.2
    bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
    betternether: Better Nether 5.1.3
    betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
    calio: Calio 1.3.0
    cardinal-components-base: Cardinal Components API (base) 3.1.1
    cardinal-components-entity: Cardinal Components API (entities) 3.1.1
    cardinal-components-level: Cardinal Components API (world saves) 3.1.1
    cloth-basic-math: cloth-basic-math 0.6.0
    cloth-config2: Cloth Config v5 5.1.40
    dataattributes: Data Attributes 1.0.6
    fabric: Fabric API 0.42.1+1.17
    fabric-api-base: Fabric API Base 0.4.0+5847535018
    fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
    fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
    fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
    fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
    fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
    fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
    fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
    fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
    fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
    fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
    fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
    fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
    fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
    fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
    fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
    fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
    fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
    fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
    fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
    fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
    fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
    fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
    fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
    fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
    fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
    fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
    fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
    fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
    fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
    fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
    fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
    fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
    fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
    fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
    fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
    fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
    fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
    fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
    fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
    fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
    fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
    fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
    fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
    fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
    fabricloader: Fabric Loader 0.12.5
    fallflyinglib: FallFlyingLib 3.0.0-beta.2
    iris: Iris 1.1.2+build.9
    java: OpenJDK 64-Bit Server VM 17
    minecraft: Minecraft 1.17.1
    modmenu: Mod Menu 2.0.14
    net_objecthunter_exp4j: exp4j 0.4.8
    omega-config: OmegaConfig 1.0.8
    origins: Origins 1.1.4
    placeholder-api: Placeholder API 1.1.1+1.17.1
    playerabilitylib: Pal 1.3.0
    playerex: PlayerEx 3.0.7
    reach-entity-attributes: Reach Entity Attributes 2.1.1
    relicex: RelicEx 3.0.2
    repurposed_structures: Repurposed Structures 2.5.7+1.17.1
    sodium: Sodium 0.3.2+build.7
    trinkets: Trinkets 3.0.4
    xaeroworldmap: Xaero's World Map 1.18.2
    yungsapi: YUNG's API 1.17-Fabric-19
  Launched Version: fabric-loader-0.12.5-1.17.1
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  Window size: <not initialized>
  GL Caps: Using framebuffer using OpenGL 3.2
  GL debug messages: <disabled>
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Damyan\AppData\Roaming\Crystal-Launcher\instances\u.1.17.1_Vanilla_Plus\.minecraft\crash-reports\crash-2021-11-19_15.08.13-client.txt

**Comment by paulevsGitch** [comment]
You have both iris and sodium, they are not compatible (iris has its own custom build inside). This is not a BCLib issue
