### ISSUE TITLE
[Compatibility] Incompatibility with VMP mod, Planks tags related issue

### ISSUE THREAD

**Issue by Dreeam-qwq** [paulevsGitch/BCLib#60]
Version: 1.17.1
bclib: 0.5.6
VMP: [0.1.0+beta.1](https://github.com/RelativityMC/VMP-fabric/tree/ver/1.17)

Error on launch server
```
[12:04:52] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.12.12
[12:04:52] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.2.1+cf39a74318 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[12:04:52] [main/INFO]: Loading 40 mods:
	- bclib 0.5.6
	- fabric 0.44.0+1.17
	- fabric-api-base 0.4.0+cf39a74318 via fabric
	- fabric-api-lookup-api-v1 1.4.0+cb9053d118 via fabric
	- fabric-biome-api-v1 3.2.2+cf39a74318 via fabric
	- fabric-command-api-v1 1.1.4+cf39a74318 via fabric
	- fabric-commands-v0 0.2.3+cf39a74318 via fabric
	- fabric-containers-v0 0.1.13+cf39a74318 via fabric
	- fabric-content-registries-v0 0.4.1+3447790d18 via fabric
	- fabric-crash-report-info-v1 0.1.6+cf39a74318 via fabric
	- fabric-dimensions-v1 2.0.13+cf39a74318 via fabric
	- fabric-entity-events-v1 1.4.1+377137cc18 via fabric
	- fabric-events-interaction-v0 0.4.12+e99fbe1218 via fabric
	- fabric-events-lifecycle-v0 0.2.4+cf39a74318 via fabric
	- fabric-game-rule-api-v1 1.0.8+cf39a74318 via fabric
	- fabric-item-api-v1 1.3.0+6617390918 via fabric
	- fabric-item-groups-v0 0.3.2+cf39a74318 via fabric
	- fabric-lifecycle-events-v1 1.4.6+0392f3a618 via fabric
	- fabric-loot-tables-v1 1.0.5+cf39a74318 via fabric
	- fabric-mining-level-api-v1 1.0.3+cf39a74318 via fabric
	- fabric-mining-levels-v0 0.1.6+cf39a74318 via fabric
	- fabric-networking-api-v1 1.0.14+cf39a74318 via fabric
	- fabric-networking-blockentity-v0 0.2.12+cf39a74318 via fabric
	- fabric-networking-v0 0.3.3+cf39a74318 via fabric
	- fabric-object-builder-api-v1 1.11.0+f907116918 via fabric
	- fabric-object-builders-v0 0.7.7+cf39a74318 via fabric
	- fabric-particles-v1 0.2.5+cf39a74318 via fabric
	- fabric-registry-sync-v0 0.7.13+cf39a74318 via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318 via fabric
	- fabric-rendering-fluids-v1 0.2.1+cf39a74318 via fabric
	- fabric-resource-loader-v0 0.4.10+f09604ce18 via fabric
	- fabric-screen-handler-api-v1 1.1.9+cf39a74318 via fabric
	- fabric-structure-api-v1 1.1.15+cf39a74318 via fabric
	- fabric-tag-extensions-v0 1.2.3+cf39a74318 via fabric
	- fabric-tool-attribute-api-v1 1.3.2+cf39a74318 via fabric
	- fabric-transfer-api-v1 1.5.3+cf39a74318 via fabric
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.17.1
	- vmp 0.1.0+beta.1
[12:04:53] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/server/Winds/Fabric%e6%97%8b%e5%be%8b%e4%b9%8b%e5%9f%8e/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[12:04:53] [main/INFO]: Compatibility level set to JAVA_16
[12:04:53] [main/WARN]: Error loading class: carpet/patches/EntityPlayerMPFake (java.lang.ClassNotFoundException: carpet/patches/EntityPlayerMPFake)
[12:05:00] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[12:05:00] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[12:05:01] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zdm000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[12:05:01] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bclib'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$2862/0x0000000065cf9f10.apply(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
	at net.minecraft.server.Main.main(Main.java:97) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.IllegalStateException: Tag minecraft:planks used before it was bound
	at net.minecraft.class_5120$class_5121.method_26776(class_5120.java:84) ~[server-intermediary.jar:?]
	at net.minecraft.class_5120$class_5121.method_15138(class_5120.java:100) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856$class_1858.method_8108(class_1856.java:207) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.md995b20$lambda$onInit$0$1(class_1856.java:538) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856$$Lambda$2687/0x00000000670402f8.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at net.minecraft.class_1856.handler$zgj001$onInit(class_1856.java:541) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.<init>(class_1856.java:41) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8092(class_1856.java:109) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8106(class_1856.java:131) ~[server-intermediary.jar:?]
	at ru.bclib.recipes.GridRecipe.addMaterial(GridRecipe.java:78) ~[%5B前置-更好的%5Dbclib-0.5.6.jar:?]
	at ru.bclib.recipes.CraftingRecipes.init(CraftingRecipes.java:14) ~[%5B前置-更好的%5Dbclib-0.5.6.jar:?]
	at ru.bclib.BCLib.onInitialize(BCLib.java:40) ~[%5B前置-更好的%5Dbclib-0.5.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2820/0x0000000065cf9000.accept(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
	... 15 more

```

**Comment by paulevsGitch** [comment]
Looks like the issue is in [VMP Ingredient Mixin](https://github.com/RelativityMC/VMP-fabric/blob/e7c878ad8ab87bb6723bfcc21e5ea465a8578582/src/main/java/com/ishland/vmp/mixins/general/ingredient_matching/MixinIngredient.java#L37), it calls entries before tag was created/used

**Comment by paulevsGitch** [comment]
Since 1.2.5 BCLib uses TagLocation for vanilla tags, and in 1.3.0 it sill use it for all tags, so this issue will not happen again with any mod
