### ISSUE TITLE
crash upon load. entrypoint stage. 

### ISSUE THREAD

**Issue by TheRanker** [paulevsGitch/BCLib#66]
// You should try our sister game, Minceraft!

Time: 1/1/22, 1:04 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bclib'!
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.7)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.client.MinecraftClient.redirect$fni000$catchFabricInit(MinecraftClient:23978)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:452)
	at net.minecraft.client.main.Main.main(Main:199)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Tag minecraft:planks used before it was bound
	at net.minecraft.tag.RequiredTagList$TagWrapper.get(RequiredTagList:84)
	at net.minecraft.tag.RequiredTagList$TagWrapper.values(RequiredTagList:100)
	at net.minecraft.recipe.Ingredient$TagEntry.getStacks(Ingredient:209)
	at net.minecraft.recipe.Ingredient.mdbaaa28$lambda$init$3$1(Ingredient:1532)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at net.minecraft.recipe.Ingredient.<init>(Ingredient:42)
	at net.minecraft.recipe.Ingredient.ofEntries(Ingredient:111)
	at net.minecraft.recipe.Ingredient.fromTag(Ingredient:133)
	at ru.bclib.recipes.GridRecipe.addMaterial(GridRecipe.java:78)
	at ru.bclib.recipes.CraftingRecipes.init(CraftingRecipes.java:14)
	at ru.bclib.BCLib.onInitialize(BCLib.java:39)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)

-- Initialization --
Details:
Stacktrace:
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:28)
	at net.minecraft.class_310.redirect$fni000$catchFabricInit(class_310.java:23980)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

this is in a modpack im working on.  im sure its a mod interaction maybe?  i use kubejs to modify tags as well. 

using **bclib-1.2.1.jar**
fabric ;0.12.12
total mods in pack.. 275.

**Comment by TheRanker** [comment]
this is definaly a mod interaction. working on trying to figure out what one.

**Comment by TheRanker** [comment]
after removing several, re adding them... seems the error no longer exists.... (with the excate same mod versions)

may have been a mod loading thing.. but this issue seems to have fixed itself.

**Comment by paulevsGitch** [comment]
> Tag minecraft:planks used before it was bound

The reason is same as [here](https://github.com/paulevsGitch/BCLib/issues/60), so this issue is duplicate
