### ISSUE TITLE
Missing parser args `port` in `bclib_callServerFix`

### ISSUE THREAD

**Issue by Vigilans** [paulevsGitch/BCLib#93]
https://github.com/paulevsGitch/BCLib/blob/a724f81091f8c4ea0007448df0e848b10c7e1b0c/src/main/java/ru/bclib/mixin/common/MainMixin.java#L24-L40

OptionParser now only accepts two arguments: `universe` and `world`, which will cause arguments like `port` to crash the server starting:

```log
[Server] [14:48:11] [main/FATAL]: Failed to start the minecraft server
[Server] joptsimple.UnrecognizedOptionException: port is not a recognized option
[Server]        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[jopt-simple-5.0.4.jar:?]
[Server]        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510) ~[jopt-simple-5.0.4.jar:?]
[Server]        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[jopt-simple-5.0.4.jar:?]
[Server]        at joptsimple.OptionParser.parse(OptionParser.java:396) ~[jopt-simple-5.0.4.jar:?]
[Server]        at net.minecraft.server.Main.handler$zea000$bclib_callServerFix(Main.java:528) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:131) [server-intermediary.jar:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[Server]   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[Server]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[Server]         at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
```
Available arguments:
https://minecraft.fandom.com/wiki/Tutorials/Setting_up_a_server#Minecraft_options

**Comment by quiqueck** [comment]
Thank you for reporting. Will be fixed in 1.3.1

**Comment by quiqueck** [comment]
1.3.1 was just released and should fix this crash. Please re-open this issue if you still have the same problem after upgrading.

**Comment by Vigilans** [comment]
@quiqueck The problem is solved, but it seems that the version number in `farbic.mod.json` forgot to be updated after bclib updated to 1.3.1:

```
{
	"schemaVersion": 1,
	"id": "bclib",
	"version": "1.3.0",
```
